### ISSUE TITLE
I cannot access the Zuul resource after access token expires

### ISSUE THREAD

**Issue by fghorbel** [galovics/google-oauth2-spring#1]
Hi, 

Could you please tell me why after the access token expires, i cannot access the zuul resource. 

I got the following error. 

```
20:22:26.600 [qtp798874225-540] DEBUG o.s.s.w.a.ExceptionTranslationFilter: Authentication exception occurred; redirecting to authentication entry point
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
```

I have to login again from google to regain access. 

Thank you.

**Comment by galovics** [comment]
Hey @fghorbel,

That's the correct behavior. When the access token expires, you will not be able to use it anymore. 

There is a possibility to use a refresh token (which as far as I remember, Google doesn't support) to acquire a new token without logging in again.
The other possibility is to write a custom login which logs you in again, therefore getting a new, valid access token.

Best,
Arnold

**Comment by fghorbel** [comment]
Hey Arnold, 

Yes, Google does support the refresh_token through `https://www.googleapis.com/oauth2/v4/token` endpoints.  

Thank you for your response. 

Best, 
Fadel
